### ISSUE TITLE
Mouse movement freezes randomly

### ISSUE THREAD

**Issue by Minikiin** [uku3lig/oldinput#2] opened 2022-10-22 23:22 UTC
In the video I tried to keep the movement at a constant pace so you can clearly tell when it just freezes on 4 different occasions
https://youtu.be/McWd03yYawg (not sure how to do embed video if that's even a thing)

Version: OldInput 1.1.1
MC version: 1.8.9
Forge: 11.15.1.2318

**Comment by uku3lig** [comment] 2022-10-25 12:34
Pretty weird, this issue was supposed to be fixed in 1.1.1. Do you still have the logs?

**Comment by Minikiin** [comment] 2022-10-31 23:46
Just a latest.log? I made a new instance to make it as clean as possible I suppose
https://pastebin.com/AUFLmnJB

**Comment by jakewdr** [comment] 2022-11-06 09:40
I'm getting the same issue including micro stutters.
1.12.2 Forge using Foamfix, bettterfps, phosphor and reauth 
It also just randomly stopped working on hypixel

**Comment by uku3lig** [comment] 2022-11-07 22:25
> https://pastebin.com/AUFLmnJB

Pretty weird issue, could you try using [this JDK](https://adoptium.net/temurin/releases?version=8) instead, and then sending me the latest.log again?

(I'd also recommend updating your Windows, but that's up to you)

**Comment by uku3lig** [comment] 2022-11-09 18:34
Upon further inspection, I am able to reproduce the issue, and it looks like it's a jinput problem, which just disables mouse input when rescanning, so I really only see 2 options here:

* Switch back to a /rescan command
* Or use a completely different input library.

Jinput seems just old and janky, and I don't really want to keep messing with it, so I'll try looking for another library.

**Comment by uku3lig** [comment] 2023-09-02 14:39
Fixed by #5

**Closed as completed by uku3lig** 2023-09-02 14:39 UTC
