### ISSUE TITLE
mouse cursor freezing and don't know how to fix

### ISSUE THREAD

**Issue by Ocilip849** [uku3lig/oldinput#4] opened 2023-05-01 03:22 UTC
good mod but my mouse cursor keeps freezing for whatever reason
version 1.8.9
launcher/client feather client
oldinput 1.1.1

**Comment by Ocilip849** [comment] 2023-05-01 03:45
pls help

**Comment by uku3lig** [comment] 2023-05-01 13:41
duplicate of #2

**Comment by Ocilip849** [comment] 2023-05-01 22:59
no like it completely freezes in that one spot and i cant move it (its different from that one)

**Comment by uku3lig** [comment] 2023-05-01 23:49
my bad, this might be an issue to do with feather client. could you please send a logfile and maybe try with another launcher to see if the issue persists?

**Comment by Ocilip849** [comment] 2023-05-02 02:43
also i forgot to mention, this issue occurs every a couple of hours

log file:
[latest.log](https://github.com/uku3lig/oldinput/files/11369358/latest.log)

my mods folder:
![image](https://user-images.githubusercontent.com/132243958/235569181-ae0684eb-98e4-4a3e-abd5-283d6378bdb3.png)
![image](https://user-images.githubusercontent.com/132243958/235569258-64f4f4ac-2001-4cf6-b632-3244260585b9.png)

**Comment by Ocilip849** [comment] 2023-05-02 02:50
![image](https://user-images.githubusercontent.com/132243958/235569240-4901955d-4a34-4453-83fd-9c1557c02b25.png)

**Comment by uku3lig** [comment] 2023-05-02 23:05
it's weird, i don't really see anything that could cause the issue. have you tried with a different launcher?

**Comment by Ocilip849** [comment] 2023-05-03 01:59
i removed the mcmouser mod and it turned out to be the issue. i didnt know that mcmouser was for macOS only until i read the desc. mb for wasting your time i will be more observant before downloading mods next time

**Comment by uku3lig** [comment] 2023-05-03 11:05
no problem!

**Closed as completed by uku3lig** 2023-05-03 11:05 UTC
